### ISSUE TITLE
No video hardware acceleration with Mesa 22.2 RC1 and higher

### ISSUE THREAD

**Issue by mihailim** [ernstp/ppa-mesarc#11]
Hi!

Upstream Mesa has stopped building in by default support for H.264 and H.265 decoding and encoding, as well as VC-1 decoding. Support isn't dropped, it's just that now we need to **explicitly** activate it at build time -- see [Debian bug 1016687](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016687) for details.

As it stands now, with `22.2.0+git2209282103.897e382d9d`, the VA profile looks like this:

```
libva info: VA-API version 1.11.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_11
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.11 (libva 2.1.0)
vainfo: Driver version: Mesa Gallium driver 22.2.0 for AMD Radeon RX 590 Series (polaris10, LLVM 11.0.0, DRM 3.47, 5.19.12-xanmod1)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
```

The correct firmware is present, and the system exposes the now-missing entrypoints with 22.1 or older.

The upstream Debian fix was to include `-Dvideo-codecs="vc1dec, h264dec, h264enc, h265dec, h265enc"` in the build defs, as per https://salsa.debian.org/xorg-team/lib/mesa/-/commit/78fe00e7470aab38ab214161e28557ef2ff4d9ff -- could you maybe take a look at doing something similar? Or alternatively, depending on how you generate things (I admit I didn't look :blush:) via meson_options.txt as per https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016687#20

Thank you!

**Comment by ernstp** [comment]
Ah thanks for the heads up. Will probably fix it on the weekend.
