### ISSUE TITLE
Dependencies broken with most recent release

### ISSUE THREAD

**Issue by srett** [ernstp/ppa-mesarc#12]
I'm setting up a fresh Ubuntu 20.04 (focal) environment with deboostrap:
```
debootstrap --variant=minbase --arch=amd64 \
   --include="build-essential,dbus,binutils,lsb-release,wget,rsync,nano,software-properties-common" \
   "focal" "/tmp/testroot" ""http://ftp.fau.de/ubuntu"
```
Change `sources.list` to add updates/security/etc.:
```
deb http://ftp.fau.de/ubuntu focal main restricted universe
deb http://ftp.fau.de/ubuntu focal-updates main restricted universe
deb http://ftp.fau.de/ubuntu focal-security main restricted universe
```

Then I add the PPA:
```
add-apt-repository ppa:ernstp/mesarc
```

After that, e.g. `apt install wireshark` gives me:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wireshark : Depends: wireshark-qt (= 3.2.3-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Chasing down the dependency chain this is because `libegl-mesa0` depends on `libwayland-client0 (>= 1.20.0)` but there only is `1.18.0-1ubuntu0.1` available.

I guess I can just look for a PPA with more recent builds of that, but the current situation is... not ideal? I get that this is for testing mostly, but if you have an existing setup with this PPA and do `apt full-upgrade` you're left without a working graphical session as far as I can tell.

So, not sure whether this is "works as expected" or an accident; I thought I'm gonna open an issue just in case.

**Comment by ernstp** [comment]
Aah I think I know what that is...

**Comment by ernstp** [comment]
Should be solved now.
