### ISSUE TITLE
Is this commit 20761 in Mesa from this PPA?

### ISSUE THREAD

**Issue by YamiYukiSenpai** [ernstp/ppa-mesarc#16]
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/20761

I'm just wondering as this may help improve stability in *Halo: Infinite*.

At the moment, I don't have plans to play the game until Season 3 comes out.

**Comment by ernstp** [comment]
I'm happy that you're enthusiastic about my PPA but stop spamming please. :-)
I just compile whatever is in the branch, and you have the SHA1 in the version.
