### ISSUE TITLE
Wayland sleep bug

### ISSUE THREAD

**Issue by viggen66** [ernstp/ppa-mesarc#19]
Wayland ppa:ernstp/wayland, gives graphics glitches after resume from sleep, only way to fix is to force shutdown and reboot.

**Comment by ernstp** [comment]
Hi, nice to see your interest in ppa:ernstp/wayland, but I have to say this is very much a poor bug report. You don't give a single detail about the problem or anything else....

**Comment by viggen66** [comment]
Sorry, can't report better than this on the bug, the computer becomes completely useless,  also I have tried on a straight clean KDE Neon install, and the bug is present prior to the Wayland libraries update, so the bug is not from this updated Wayland, is something else embedded in the operating system, apart from this, which is unrelated to this PPA, until now I didn't notice any bug or glitch, it works pretty well, thanks

**Comment by ernstp** [comment]
Next time you should include, the exact version of your operating system, what type of hardware you're using, GPU model, GPU driver version, and preferably system log files.

>  the bug is not from this updated Wayland

Well then it's not really related to my PPA, I just help with compiling the upstream sources. So you should report directly to upstream! Hope you can find a solution!

**Comment by viggen66** [comment]
Thanks
