### ISSUE TITLE
ACO PPA: Black screen on vulkan games

### ISSUE THREAD

**Issue by Alexmitter** [ernstp/ppa-mesarc#2]
Hello, please excuse me to open a ticket here, since the build run on 2020-05-01 I am only getting a black screen running Vulkan games. A ppa-purge, the standard ubuntu 20.04 mesa packages will let my games work again. I also tried the builds from today and the issue still persists.

I expect this to be a regression on the mesa git, so you probably are able to tell me that you are able to reproduce my issue but if it isnt and you are not able to reproduce it, please tell me that.

**Comment by ernstp** [comment]
Sure, let's see if we can figure out what's going on!
I had some artifacts before and I saw some reverts on the ML, I thought todays build would fix that...
But I didn't see any black screen.

DXVK or Linux games? Which GPU? Other info?

**Comment by Alexmitter** [comment]
I mainly tried it out with GTA5 over DXVK, the screen stays black and you hear for about 30 seconds the usual sounds of it starting up. Another game I tried out was Doom 2016 as a vulkan native title and shadow of the tomb raider as a linux native title where even the resolution setting window all feral games have only renders a black box.
Ubuntu 20.04, Radeon VII. Any other informations needed?

**Comment by ernstp** [comment]
With 2020-05-04 the corruption I had is gone and I can run both Doom and SotTR.

Can you run vkcube?
LIBGL_DEBUG=verbose glxgears?

**Comment by Alexmitter** [comment]
![image](https://user-images.githubusercontent.com/6940479/80997290-6105a600-8e41-11ea-91ed-05f98f60c7ac.png)
Output from glxgears with the debug flag:
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/alexmitter/.drirc: No such file or directory.
libGL: using driver amdgpu for 4
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/alexmitter/.drirc: No such file or directory.
libGL: pci id for fd 4: 1002:66af, driver radeonsi
libGL: MESA-LOADER: dlopen(/usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so)
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/alexmitter/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/alexmitter/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/alexmitter/.drirc: No such file or directory.
/usr/share/libdrm/amdgpu.ids version: 1.0.0
libGL: Using DRI3 for screen 0
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.

I have to add one info as this is probably important and sorry that I forgot to mention that, I am running on Gnome with Wayland. I will try if it works in Xorg.

**Comment by Alexmitter** [comment]
Tried it and yes, I can confirm that it works under Xorg but not under Wayland/Xwayland.

**Comment by ernstp** [comment]
Ah I see! I've been running Wayland myself a lot lately but not right now, back on Xorg.
Sounds like it could be this? https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4869
or https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4885  maybe...

**Comment by Alexmitter** [comment]
Sorry if I get this wrong, I think you build your PPA from the master branch, but both MR's are open so not in master yet.

**Comment by Alexmitter** [comment]
Good news, I just updated to the builds that were done 50 minutes ago and vkcube, SotTR and GTA5 load up just normal.

**Comment by ernstp** [comment]
There's no 50 minute ago build... ?

**Comment by Alexmitter** [comment]
To be honest I am not sure now myself, I thought I saw packages build 50 minutes ago yesterday and updated to those.
When I installed the PPA again yesterday it did install 2020-05-04  17:34:26 20.2.0~git2005010751.cc2c3b41b86~f~mesaaco0
When I saw this update it was 2020-05-04  22:12:08: 
20.2.0~git2005041406.cb1e0db23e3~f~mesaaco0

This is probably just me messing up something in my brain, so anyways Vulkan is working again under Wayland so I guess we can close it.

**Comment by ernstp** [comment]
Yeah great! No idea if people are using my stuff so it's fun to get some feedback! :-)
