### ISSUE TITLE
Signature by key  uses weak algorithm (rsa1024)

### ISSUE THREAD

**Issue by Goopher97** [ernstp/ppa-mesarc#22]
sudo add-apt-repository ppa:ernstp/mesarc

/usr/lib/python3/dist-packages/apt/cache.py:562: Warning: 
W:https://launchpad.proxy.ustclug.org/ernstp/mesarc/ubuntu/dists/noble/InRelease: Signature by key 
177961E789BE960FE5E59170B78C97EF9B2235DD uses weak algorithm (rsa1024)
  res = self._cache.update(fetch_progress, slist, pulse_interval)

please fix

have good day.

**Comment by ernstp** [comment]
Just waiting for Ubuntu to sort this out, nothing I can do:

https://discourse.ubuntu.com/t/new-requirements-for-apt-repository-signing-in-24-04/42854/19

https://answers.launchpad.net/launchpad/+question/809194

**Comment by ernstp** [comment]
If you delete the source.list.d file and run apt-add-repository again, Ubuntu have upgraded the Launchpad keys now!
