### ISSUE TITLE
missing codecs in va-api

### ISSUE THREAD

**Issue by oyvindln** [ernstp/ppa-mesarc#23]
vp9 and av1 is missing from va-api

I think it's probably due to not being enabled here
https://github.com/ernstp/ppa-mesarc/blob/e9ce1f488b57691245b6cc5eee081df7815f7333/mesa-git/debian/noble/rules#L148

The upstream rules file changed to using ```confflags_GALLIUM += -Dvideo-codecs="all"``` after the new codecs were added in 24.0 instead of adding each manually from what I could see
https://git.launchpad.net/ubuntu/+source/mesa/commit/debian/rules?id=08f9a0a3c7e6756438fe603fb9094bb4553ff83f

**Comment by ernstp** [comment]
Thanks for the detailed tip. Working on it, doing a big update...

**Comment by ernstp** [comment]
Should be fixed now, can you check @oyvindln ?

**Comment by oyvindln** [comment]
Yep it's sorted
