### ISSUE TITLE
32 bits Mesa NVK build

### ISSUE THREAD

**Issue by Nautilus-1021** [ernstp/ppa-mesarc#24]
I am trying to play games with my GTX 1650 and the Nouveau driver, and I encountered an error while using Wine-GE-Proton, which uses DXVK. I don't know why, DXVK needs the 32 bits version of the driver, so it just failed.

So is it possible to add a 32 bits build of the Mesa NVK driver ?

**Comment by ernstp** [comment]
Which Ubuntu are you on?

The Nouveau driver has got a lot of build dependencies these days and Ubuntu has really locked down the 32-bit support, so it might be hard. But I can take a look again in the coming week!

**Comment by Nautilus-1021** [comment]
I am on Ubuntu Noble 24.04.1

**Comment by ernstp** [comment]
It's not really possible right now, Ubuntu have dropped too much 32-bit stuff. Actually Debian is better here, they have i386 fully up and running still.
