### ISSUE TITLE
Any chance of a bionic build of corectrl?

### ISSUE THREAD

**Issue by nathan-c** [ernstp/ppa-mesarc#3]
Looks like Ubuntu 20.04 and 19.04 have builds but not 18.04. Is there any chance this could be added?
![image](https://user-images.githubusercontent.com/13839027/84249206-602bf800-ab02-11ea-8fb7-6c457fc3ad69.png)

**Comment by ernstp** [comment]
I did try it and it fails for a couple of reasons, so I gave up and didn't bother digging further into it. It's probably not impossible though!

**Comment by ernstp** [comment]
Done!
