### ISSUE TITLE
epic-games-store under Lutris black screen after every update/upgrade

### ISSUE THREAD

**Issue by MajorGonzo** [ernstp/ppa-mesarc#4]
Hello.  I hope this is the right place for this.  I installed your branch for mesa to run corectrl (thanks for that, btw).  However, since then, it seems every time I have an update that includes the mesa branch, Epic Games Store, when launching from Lutris, just has a black screen in it's window (still has min/max/close buttons) and the loading bar across the bottom (blue swirl line).  If I reinstall Epic Games Store, it works again.  Not a huge deal, since there's a workaround, but I'm willing to work with you to figure out what's wrong.  Happened again this morning, so I grabbed the --upgradable and upgrade screen messages to see if this is even connected at all to this branch.  What do you think?
[epic-store.log](https://github.com/ernstp/ppa-mesarc/files/5696596/epic-store.log)

**Comment by ernstp** [comment]
Hi!
This is not related to this specific ppa, just with updating Mesa in general I would say. Perhaps related to the shader cache?
