### ISSUE TITLE
Graphic Bug effects the whole system after starting Prominence Poker.

### ISSUE THREAD

**Issue by JokerGermany** [ernstp/ppa-mesarc#5]
I don't know if the problem is your ppa, the kernel or both.
Thats the Reason why i open this issue.

Ubuntu Mate 20.04
AMD Vega 56
The problem **didn't** occur with 5.4.0-56-generic

Everytime i start the game Prominence Poker with proton I get this:
[![IMG_20201229_100852.th.jpg](https://pic-hoster.net/images/2020/12/29/IMG_20201229_100852.th.jpg)](https://pic-hoster.net/image/QpfV6)
I think everything is running in the Background quite normal (I think i see changes "behind" the graphic bugs) and the curser (which can also be seen on the pciture) is normal.
But i can't make any input.

I switched back to the old kernel, but i want to report this, because i couldn't use this kernel version for an ethernity^^

Another proton game (Rocket League) didn't crash, but i only tested it for a short time. 
(When starting Prominence Poker the crash is happening!)

I reported this here, too:
https://ubuntu-mate.community/t/graphic-bug-with-kernel-5-4-0-58-generic-where-do-i-report-this/23315

**Comment by JokerGermany** [comment]
Okay, it occurs with Kernel 5.4.0-56, too.
I will remove this ppa and test if it changes anything.

**Comment by JokerGermany** [comment]
Okay, i think it's a mesa related bug.
Without your ppa Prominence Poker freezes with a black screen, but the system isn't effected.
Will try your stable ppa now.

**Comment by JokerGermany** [comment]
Okay: 
my conclusion:
Without your ppa only the game freezes.
With your ppa the whole System freezes.

**Comment by JokerGermany** [comment]
Is there any possibility to get back to git2012162009.4a87e444134?

**Comment by JokerGermany** [comment]
Okay, it has something to do with proton-ge, too:
https://github.com/GloriousEggroll/proton-ge-custom/releases
Proton-5.9-GE-8-ST => Whole System crash
Proton-5.21-GE-1 => Game Crash

Proton 5.13-4 => Looks like it works

**Comment by JokerGermany** [comment]
Okay, it has something to do with proton-ge, too:
https://github.com/GloriousEggroll/proton-ge-custom/releases
Proton-5.9-GE-8-ST => Whole System crash ( https://github.com/GloriousEggroll/proton-ge-custom/commit/f65dbb82c4c1b7f68adb23fba803a88438c17310 )
Proton-5.21-GE-1 => Game Crash ( https://github.com/GloriousEggroll/proton-ge-custom/commit/db901b1f48b10c1fb54fd70bb7b6666e09579055 )

Proton 5.13-4 => Looks like it works

**Comment by ernstp** [comment]
Hi! It's nice to see that you're using my PPA, however unless it's a packaging issue or something with a compiler flag perhaps I can't help you. You should report it to mesa itself at: https://gitlab.freedesktop.org/mesa/mesa/-/issues
