### ISSUE TITLE
Sync x-swat mesa debian files

### ISSUE THREAD

**Issue by bluntelk** [ernstp/ppa-mesarc#6]
Heya,

Been using your PPA for a while now - love your work!

Was wondering if it was possible to sync the mesa x-swat debian package building files? https://git.launchpad.net/~ubuntu-x-swat/mesa/tree/debian?h=ubuntu-focal

they have added in mesa's shiny new opengl over vulkan "Zink" driver  (in the rules file) :)

Again, Thanks for providing this PPA - it's pretty awesome!

**Comment by ernstp** [comment]
I'll look into it this week!

**Comment by bluntelk** [comment]
Thanks for this!

I just checked and ran some things with zink :D

**Comment by ernstp** [comment]
You're welcome! I did most of the work in cd21ec6fd7e85c88e6db86fb91295f100f8f43e3 and then a couple of followup commits... ;-)
