### ISSUE TITLE
Missing CoreCTRL for Ubuntu 21.04

### ISSUE THREAD

**Issue by b3nis** [ernstp/ppa-mesarc#7]
Hey!

I really love CoreCtrl and just installed 21.04 (wanna get that sweet Wayland working) - but no Corectrl :-| Tried with groovy resp. but missing some library that I cannot figure out how to install.

If you would like to add CoreCtrl for 21.04 I would be super grateful (and happy again).

Btw, are you Swedish? Anyway, greetings from Stockholm :-)

**Comment by ernstp** [comment]
That's strange, it looks like I deleted that for some reason. I'll rebuild it!

Hehe yeah I'm from Sweden, hej hej :-)

**Comment by b3nis** [comment]
Awesome! Thanks! How does it usually take? If I am gonna give it a try before bed or wait until tomorrow 8-)

**Comment by ernstp** [comment]
It's available now.

**Comment by b3nis** [comment]
I saw that - big thanks! Installation worked flawless.
