### ISSUE TITLE
Latest update broke high res grfx on ASUS 990FX/AMD Phenom X6/Powercolor HD 7950!

### ISSUE THREAD

**Issue by BayouGuru67** [ernstp/ppa-mesarc#8]
Immediately following the latest driver update, the 1080p desktop was broken/frozen on my system.  It still technically functioned, as if you knew the keystrokes, you could do things as long as you didn't mind having zero visual indication of what you were doing other than hard drive activity, as the video was frozen solid.  

It would freeze during the rebooting process as soon as it would try to display the Plasma desktop.  

Only by either using the hardware switch or memorized [CAD]-[return] Reboot sequence then booting into recovery mode with low res software rendering could I get a functional desktop back.  

None of the usual commands you find when searching for "frozen desktop" or various permutations of it involving xorg, xrandr, etc... made any difference.  

Not being an expert in Linux, I ended up reinstalling the OS 2x. Yes, twice, because when I had first reinstalled Kubuntu, then enabled your repository and installed CoreCtrl, it immediately broke my fresh install just like it did before, which I considered a 50/50 win/fail, for even though it broke my system, it also confirmed for me exactly what it was that originally broke it. I didn't make the same mistake again.

System Hardware info as follows:

Mobo:  Asus Sabertooth 990FX
CPU:  AMD Phenom x6 1075T (not running turbo mode or OC)
8 GB 1600MHz SDRAM
GPU:  Powercolor AMD HD7950
OS:  Kubuntu 20.04.3LTS

**Comment by ernstp** [comment]
Hi! Right, I just compile mesa, if there are issues in actual Mesa you have to look there for solutions!

I search a bit for you, could be this: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5989 ?!

Go there and add some details about your system, and maybe any dmesg logs etc...

**Comment by ernstp** [comment]
If you want to roll back the changes you might be able to switch to the text console with Ctrl-Alt-F4 etc, and then run the command
`sudo ppa-purge ppa:ernstp/mesarc`

**Comment by ernstp** [comment]
Latest build should have a fix for this now!
