### ISSUE TITLE
ThinkPad T510 is using llvmpipe for graphics instead of Intel HD 

### ISSUE THREAD

**Issue by YamiYukiSenpai** [ernstp/ppa-mesarc#9]
My T510 was upgraded with a Intel Core i7 640M.  I discovered that it's using llvmpipe instead of Intel HD for graphics, and I don't know why.  I have everything related to Intel graphics & mesa installed on the system.

```
$ sudo lshw -c display
  *-display                 
       description: VGA compatible controller
       product: Core Processor Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1600,2700
       resources: irq:27 memory:f2000000-f23fffff memory:d0000000-dfffffff ioport:1800(size=8) memory:c0000-dffff
```

```
$ DRI_PRIME=0 glxinfo | grep "OpenGL renderer"
OpenGL renderer string: llvmpipe (LLVM 13.0.1, 128 bits)
```

I tried both 5.15 & [Liquorix's 5.16](https://liquorix.net/) kernels, along with  your Mesa, but none worked.  Had to use yours because Mesa in Ubuntu repo wasn't working properly (constant freezes), and necessitated me to add this PPA (until today).  Reverting back to official repo solved it.

[Here](https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1960403/comments/16)'s the link to Launchpad bug report that may be the cause as to why my laptop was using LLVMpipe.

OS: Kubuntu 22.04

**Comment by ernstp** [comment]
You're CPU is 12 years old, there won't be any updates for it. Just stick to official Ubuntu drivers, they will be the same.
It's because of https://www.phoronix.com/scan.php?page=news_item&px=Mesa-Classic-Retired  you get LLVMpipe.

**Comment by ernstp** [comment]
Though there might be some new replacement drivers I could enable instead...

**Comment by YamiYukiSenpai** [comment]
> Though there might be some new replacement drivers I could enable instead...

Sure hope so.  yes, it's old, but it's perfect to use whenever I'm running on the treadmill.
